class BaseConfig:
    API_TITLE = 'Revenue API'
    API_VERSION = 'v1'
    OPENAPI_VERSION = '3.0.3'
    OPENAPI_JSON_PATH = 'openapi/revenue.json'
    OPENAPI_URL_PREFIX = '/'
    OPENAPI_REDOC_PATH = '/redoc'
    OPENAPI_REDOC_URL = 'https:/ /cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js'
    OPENAPI_SWAGGER_UI_PATH = 'docs/revenue'
    OPENAPI_SWAGGER_UI_URL =  'https://cdn.jsdelivr.net/npm/swagger-ui-dist/'